language: c

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode9.3

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq build-essential curl; fi

script:
    - while sleep 300; do echo "=====[ $SECONDS seconds still running ]====="; done &
    - SKIPINSTALL=yes VERBOSE=yes ./build-ffmpeg --build
    - kill %1

after_script:
    - ./build-ffmpeg --cleanup
